/**
 * bootstrap/runner.ts — one-command project workspace setup.
 *
 * `nucleus bootstrap` turns an empty folder into an agent-ready workspace:
 *
 *   profile (from answers.json or sensible defaults) → wayfinder map →
 *   skill bundle (optional externals) → subagent orchestration → AGENTS.md.
 *
 * AGENTS.md is the file omp / opencode / claude-code / codex read at session
 * start — the "system prompt" for project agents. It summarizes the profile
 * and points each agent role at its skills and the artifacts to consume.
 */

import { basename, join } from "node:path";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { buildProfile, persistProfile, type GrillAnswers } from "../grill/runner.js";
import { emptyMap, chartInitialFrontier, loadMap, saveMap } from "../wayfinder/runner.js";
import { assembleBundle } from "../loader/runner.js";
import { buildOrchestration, persistOrchestration } from "../orchestrator/runner.js";
import type { ProjectProfile, Orchestration } from "../types.js";

export const AGENTS_FILE = "AGENTS.md";

/** Read an answers file; split into keys; prune empties. */
export async function readAnswers(rootDir: string, answersFile?: string): Promise<GrillAnswers | null> {
  if (!answersFile) return null;
  try {
    const raw = JSON.parse(await readFile(answersFile, "utf8")) as GrillAnswers;
    const out: GrillAnswers = {};
    for (const k of Object.keys(raw)) if (raw[k]) out[k] = raw[k];
    return out;
  } catch {
    return null;
  }
}

/**
 * Fallback answers when the user runs `nucleus bootstrap` with no answers
 * file — the folder name becomes the project name, the rest take safe
 * defaults so the workspace is usable immediately.
 */
export function defaultAnswers(rootDir: string, domain: string): GrillAnswers {
  const name = rootDir.split(/[\\/]/).filter(Boolean).pop() ?? "untitled";
  return {
    name,
    destination: `New ${domain} project "${name}" — define the destination with the interviewer.`,
    domain,
    languages: "typescript",
    frameworks: "",
    harness: "opencode",
    tracker: "github",
    quality: "",
    "out-of-scope": "",
    glossary: "",
  };
}

/** Render the AGENTS.md the agents read at session start. */
export function renderAgentsMd(p: ProjectProfile): string {
  const roles = [
    "planner", "researcher", "implementer", "tester", "reviewer",
    "designer", "security", "docs", "improver",
  ];
  return `# Project instructions — ${p.name}

Managed by **nucleus**. Bootstrapped: ${new Date().toISOString().slice(0, 10)}.

## Mission

${p.destination}

## Domain, stack, harness

- Domain: ${p.domain}
- Languages: ${p.languages.join(", ") || "_(unspecified)_"}
- Frameworks: ${p.frameworks.join(", ") || "_(unspecified)_"}
- Agent harness: ${p.harness}
- Tracker: ${p.tracker}

## How to work in this workspace

1. **Grill, then build.** Before writing code, if the destination is fuzzy,
   run the interview again: \`nucleus init --questions\` then answer via
   \`nucleus init --answers answers.json\`.
2. **Decisions live in tickets.** Right now the wayfinder frontier is in
   \`.agent-forge/wayfinder.json\`. Resolve one ticket per session
   (\`nucleus wayfind\`).
3. **Skills are bound to roles.** \`.agent-forge/orchestration.json\` maps each
   subagent role to the skills it consults. The resolved skill list lives in
   \`.agent-forge/bundle.json\` (builtins + your \`.agent-forge/skills/\` overlay).
4. **Empty answers file is fine** — the workspace was bootstrapped with
   defaults; refine by grilling.

## Roles this harness can spawn

${roles.map((r) => `- ${r}`).join("\n")}

## Shared language

${p.glossary.length
    ? p.glossary.map((g) => `- **${g.term}** — ${g.definition}`).join("\n")
    : "_(empty — fill in the interview / as the project finds its terms)_"}

## Out of scope

${p.outOfScope.length ? p.outOfScope.map((s) => `- ${s}`).join("\n") : "_(nothing ruled out yet — keep it sharp)_"}

---

_Generated by \`nucleus bootstrap\`. Re-run it (or \`nucleus reindex\`) after
the profile changes to refresh this file._
`;
}

export interface BootstrapResult {
  profile: ProjectProfile;
  refsCount: number;
  agentsCount: number;
  agentsFile: string;
}

export async function bootstrap(opts: {
  rootDir: string;
  answersFile?: string;
  domain: string;
  installExternals?: boolean;
}): Promise<BootstrapResult> {
  const explicitAnswers = opts.answersFile
    ? await readAnswers(opts.rootDir, opts.answersFile)
    : null;
  const profilePath = join(opts.rootDir, ".agent-forge", "profile.json");
  const existing = existsSync(profilePath)
    ? (JSON.parse(await readFile(profilePath, "utf8")) as ProjectProfile)
    : null;
  const profile = explicitAnswers
    ? buildProfile(explicitAnswers)
    : existing ?? buildProfile(defaultAnswers(opts.rootDir, opts.domain));
  if (!existing || explicitAnswers) await persistProfile(opts.rootDir, profile);

  // Wayfinder map (chart the frontier; reuse an existing map).
  const existingMap = await loadMap(opts.rootDir);
  if (!existingMap) {
    const map = emptyMap(profile);
    map.tickets = chartInitialFrontier(profile);
    await saveMap(opts.rootDir, map);
  }

  // Skill bundle.
  const bundle = await assembleBundle(opts.rootDir, profile, {
    installExternals: opts.installExternals,
  });

  // Orchestration.
  const orch: Orchestration = buildOrchestration(profile, bundle, profile.destination);
  await persistOrchestration(opts.rootDir, orch);

  // AGENTS.md — the "system prompt" agents read at start.
  await mkdir(opts.rootDir, { recursive: true });
  await writeFile(join(opts.rootDir, AGENTS_FILE), renderAgentsMd(profile), "utf8");

  return {
    profile,
    refsCount: bundle.refs.length,
    agentsCount: orch.agents.length,
    agentsFile: AGENTS_FILE,
  };
}